/** Canonical public URL of the site, without a trailing slash. */
export const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000").replace(
  /\/+$/,
  "",
);

/**
 * Subdirectory the site is served from (Next `basePath`), e.g. `/Bask` on
 * GitHub project Pages. Used only by next.config — asset URLs in HTML are
 * rewritten by Next itself. Do not prefix metadata image paths with this, or
 * they resolve twice (…/Bask/Bask/og.png).
 */
export const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? "").replace(/\/+$/, "");

export const siteName = "Bask in Wardrobe";
export const tagline = "A different outfit for every occasion";
export const description =
  "Bask in Wardrobe ricorda cosa hai indossato, quando e dove. La webapp sta arrivando: lascia la tua email e sei tra le prime a entrare.";

/**
 * Both images are generated by routes that carry their file extension, so a
 * static export writes them as `og.png` and `icon.png`. Paths are root-relative
 * (`/og.png`); `metadataBase` is the public site URL, and Next's `basePath`
 * rewrites requests when the site lives in a subdirectory.
 */
export const socialCard = {
  path: "/og.png",
  width: 1200,
  height: 630,
} as const;

export const favicon = {
  path: "/icon.png",
  size: 64,
} as const;
